### ISSUE TITLE
Dựng project API Node Nest

### ISSUE THREAD

**Issue by lamhan3012cmvn** [lamhan3012cmvn/Document__2School#2]
Tuần 4

**Comment by lamhan3012cmvn** [comment]
[Link SRC]:(https://github.com/lamhan3012cmvn/NestJS_2School)

**Comment by lamhan3012cmvn** [comment]
[Link SRC](https://github.com/lamhan3012cmvn/NestJS_2School)

**Comment by lambiengcode** [comment]
Done!
